vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       rental_pictures:
           uri_prefix: /images/rental
           upload_destination: '%kernel.project_dir%/public/images/rental'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
